### PR TITLE
Update LTS Haskell

### PR DESCRIPTION
**Pull request by josefdolezal**
This PR updates stack resolver to LTS 13.10 (GHC 8.6.3). Small migration was needed JWT and GitHub modules because of API change. Replaces #48 due to CI errors.

### CODE REVIEW

**Comment by josefdolezal** [comment]
Never ending story, we also have to update docker images. From CI log:

```
ADD failed: stat /var/lib/[secure]/tmp/[secure]-builder483174460/.stack-work/install/x86_64-linux/lts-12.0/8.4.3/bin/dsw-server: no such file or directory
```

New path for builded binary should be:

```
.stack-work/install/x86_64-linux/lts-13.10/8.6.3/bin/dsw-server
```

**Comment by josefdolezal** [comment]
I rebased the branch against `develop`, but the error will probably remain (see my last comment).

**Comment by MarekSuchanek** [comment]
You will have to change the path in `Dockerfile`. Of course, it would be the best to find out a way how to get this route using some find. But really not sure if that is possible there. Probably we will have to manually change it every time we change LTS.

**Comment by josefdolezal** [comment]
My bad! I did not notice the Dockerfile inside repository. Should work now 👍

**Review by MarekSuchanek — APPROVED** [review]
Seems fine to me, good job 👍

**Comment by MarekSuchanek** [comment]
@vknaisl shouldn't this be changed as well? (Really not sure about its functionality or if "just metadata"):

https://github.com/ds-wizard/dsw-server/blob/316cb7e3b0ce41e0d5f6727f854cd372f2765d38/package.yaml#L14

**Comment by vknaisl** [comment]
> @vknaisl shouldn't this be changed as well? (Really not sure about its functionality or if "just metadata"):
> 
> [dsw-server/package.yaml](https://github.com/ds-wizard/dsw-server/blob/316cb7e3b0ce41e0d5f6727f854cd372f2765d38/package.yaml#L14)
> Line 14 in [316cb7e](/ds-wizard/dsw-server/commit/316cb7e3b0ce41e0d5f6727f854cd372f2765d38)
>  tested-with: GHC==7.6.* GHC==7.8.*

Yes, we should!

**Comment by josefdolezal** [comment]
I updated the stack resolver to `lts-13.12` with GHC 8.6.4. Hopefully will build on CI 🤞. HIE on macOS still doesn't work though 😞

**Pull request merged**
